# Generated by Django 4.2.4 on 2023-10-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=100, unique=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(max_length=30)),
                ('treatments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.specialities'),
        ),
    ]
