# Generated by Django 4.2.4 on 2024-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0006_doctorleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorLeave',
        ),
    ]
