# Generated by Django 4.2.4 on 2024-03-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0007_delete_doctorleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
