# Generated by Django 4.2.4 on 2024-02-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0004_frame_delete_spects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        
    ]
