# Generated by Django 4.2.4 on 2024-02-12 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0005_alter_frame_frame_id_delete_spects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='frame',
            name='brand_name',
            field=models.CharField(choices=[('Fastrack', 'Fastrack'), ('Titan', 'Titan'), ('Essilor', 'Essilor'), ('Ray-Ban', 'Ray-Ban'), ('Boss', 'Boss'), ('Polaroid', 'Polaroid'), ('Vogue', 'Vogue')], max_length=255),
        ),
        migrations.AlterField(
            model_name='frame',
            name='bridge_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_material',
            field=models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Wood', 'Wood'), ('Aluminium', 'Aluminium')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_style',
            field=models.CharField(blank=True, choices=[('Circle', 'Circle'), ('Rectangle', 'Rectangle'), ('Geometric', 'Geometric'), ('Square', 'Square')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='lens_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='frame',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='temple_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='frame',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        # migrations.DeleteModel(
        #     name='Spects',
        # ),
    ]
