# Generated by Django 4.2.4 on 2024-02-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0006_remove_frame_sub_category_alter_frame_brand_name_and_more'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Spects',
    #     ),
    # ]
