# Generated by Django 4.2.4 on 2024-02-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0007_delete_spects'),
    ]

    
