# Generated by Django 4.2.4 on 2024-02-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0009_remove_frame_weight_alter_frame_bridge_size_and_more'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Spects',
    #     ),
    # ]
