# Generated by Django 4.2.4 on 2024-02-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0008_delete_spects'),
        ('IrisGlowApp', '0010_delete_spects'),
    ]

   