# Generated by Django 4.2.4 on 2024-02-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0012_alter_frame_bridge_size_alter_frame_lens_width_and_more'),
    ]

    