# Generated by Django 4.2.4 on 2024-02-28 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0012_alter_frame_bridge_size_alter_frame_lens_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='frame',
            name='bridge_size',
            field=models.CharField(choices=[('15', '15 mm'), ('16', '16 mm'), ('17', '17 mm'), ('18', '18 mm'), ('19', '19 mm'), ('20', '20 mm'), ('21', '21 mm'), ('22', '22 mm'), ('23', '23 mm'), ('24', '24 mm'), ('25', '25 mm')], default='15', max_length=5),
        ),
        migrations.AlterField(
            model_name='frame',
            name='lens_width',
            field=models.CharField(choices=[('45', '45 mm'), ('46', '46 mm'), ('47', '47 mm'), ('48', '48 mm'), ('49', '49 mm'), ('50', '50 mm'), ('51', '51 mm'), ('52', '52 mm'), ('53', '53 mm'), ('54', '54 mm'), ('55', '55 mm'), ('56', '56 mm'), ('57', '57 mm'), ('58', '58 mm')], default='15', max_length=5),
        ),
        migrations.AlterField(
            model_name='frame',
            name='temple_length',
            field=models.CharField(choices=[('140', '140 mm'), ('141', '141 mm'), ('142', '142 mm'), ('143', '143 mm'), ('144', '144 mm'), ('145', '145 mm'), ('146', '146 mm'), ('147', '147 mm'), ('148', '148 mm'), ('149', '149 mm'), ('150', '150 mm'), ('151', '151 mm'), ('152', '152 mm'), ('153', '153 mm'), ('154', '154 mm'), ('155', '155 mm'), ('156', '156 mm'), ('157', '157 mm'), ('158', '158 mm')], default='15', max_length=3),
        ),
        
        migrations.AddField(
            model_name='usercart',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IrisGlowApp.frame'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
