# Generated by Django 4.2.4 on 2024-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0015_order_orderitem_shippingaddress_delete_spects'),
    ]

   
