# Generated by Django 4.2.4 on 2024-03-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0016_delete_spects'),
    ]

    
    
