# Generated by Django 4.2.4 on 2024-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0017_delete_spects'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        
    ]
