# Generated by Django 4.2.4 on 2024-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0019_paymentp_delete_spects'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentp',
            name='purchased_items',
            field=models.JSONField(blank=True, null=True),
        ),
       
    ]
